### PR TITLE
Refactor service data flow

### PR DESCRIPTION
**Pull request by HeyItsBATMAN**
### What?

This PR is an attempt to clean up big services, mainly the `ProcessingService` and switch their most accessed variables to RxJS `Subject`s & *Observable`s.

This includes:
- renaming things for humans, so new contributors might have an easier time understanding what a variable is needed for.
- removing duplicate variables from components & services that used to just copy the current value from `ProcessingService`, which would in turn never know if something gets updated elsewhere
- moving data back to the services
- combining variables that share the same context to objects
- getting rid of side effects

Ideally, this should work as a drop-in replacement.

### Why was this done?

Even as one of the core developers, it was not always easy to understand or debug how the data flows from services to components in the Viewer, or how components modified service data. This slows down feature development and blocks-off potential new developers.

### CODE REVIEW

**Comment by HeyItsBATMAN** [comment]
@ZetOE what's your opinion on this?

**Comment by ZetOE** [comment]
Very good and very helpful (especially for external developers)!

**Comment by ZetOE** [comment]
@HeyItsBATMAN sorry, I already merged the branch after I commented - not sure if that was your intention when you tagged me here?

**Comment by HeyItsBATMAN** [comment]
@ZetOE I wanted to do some more testing beforehand. I'm gonna revert the merge and test some more

**Comment by ZetOE** [comment]
Jap looks perfect. I remember that I went through all these things before we finished because it was always messy. And I think it obviously had more potential to be cleaner. So thanks! And: sorry for the merge!

**Pull request merged**
