### PR TITLE
Refactor code and adjust styling of EntityFeatureSettings and its descendants

### PR DESCRIPTION
**Pull request by HeyItsBATMAN**
### What?

This PR simplifies the code used in the `EntityFeatureSettings` components, while cleaning up the settings wizard used to guide the user through setting up their entity for the Kompakkt Viewer.

### Why?

The settings process of uploading something to Kompakkt was a bit unorganized, which could lead to users not actually taking care of their settings during the upload process.

### How?

- Uses expansion panels to neatly organize available settings
- Uses colors and meaningful descriptions on the buttons
- Puts setting the preview image closer to background & light settings, making it easier to adjust quickly
- Prevents users from skipping ahead in the wizard (which was a bug. Mesh settings could be skipped)
- Uses labels and prefixes for form inputs to give the user more information while using less space
- Cleans up the TypeScript code hidden in the back
- **Update:** To match the new styles, the compilation browser has also been updated

## Checklist before merging

This is a large pull request, so testing on the following needs to be done before merging:

- [ ] Do all helpers during upload work?
- [ ] Can settings be changed during upload and are they applied in the scene?
- [ ] Can settings be changed after upload and are they applied in the scene?
- [ ] Can settings changed after upload be saved and updated?
- [ ] Are annotations that were created prior to this Pull Request at their correct locations?
- [ ] Are annotations that were created after this Pull Request at their correct locations?
- [ ] Are compilations loaded and correctly displayed in the `CompilationBrowser`?

#### Settings

01_initial
02_helpers
03_scale
04_orientation
05_preview
06_final

#### Compilation Browser

Screenshot from 2023-04-21 16-09-46

### CODE REVIEW

**Comment by HeyItsBATMAN** [comment]
@ZetOE this is not done yet, but what do you think of these changes?

The visual changes can be separated from the typescript cleanup, but I feel like this greatly improves the user experience when navigating through the available settings.

**Comment by luguenth** [comment]
Hey @HeyItsBATMAN , nice work! Seems so much smoother. headlessly jumped in and merged it in our code until I realized you said it's not finished yet. Do you know in what time this might be ready? Also can you also add the new interfaces on common on a pull request so maybe i can already look in the new interfaces as well 😇

**Comment by ZetOE** [comment]
Hey @HeyItsBATMAN 
I agree to @luguenth -> great job! I agree with all your changes and improvements. I will also look into the nonvisible changes. Thank you and sorry for my late reply, the last weeks have been really packed.

**Comment by HeyItsBATMAN** [comment]
@Grizzly127 This is the settings component @lozanaross talked about in the meeting.
Feel free to drop any suggestions here.

**Comment by HeyItsBATMAN** [comment]
Closing this, as this PR is outdated compared to the more current Angular 18 branches

**Pull request closed without merging**
